//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWS.PayrollVouchers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSVPEntities : DbContext
    {
        public CSVPEntities()
            : base("name=CSVPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblTransactionDetail> tblTransactionDetails { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblWebServiceSetting> tblWebServiceSettings { get; set; }
        public virtual DbSet<tblDocumentNumber> tblDocumentNumbers { get; set; }
        public virtual DbSet<tblDocumentNumberAudit> tblDocumentNumberAudits { get; set; }
        public virtual DbSet<tblGeneralSetting> tblGeneralSettings { get; set; }
        public virtual DbSet<tblTransactionDetailAudit> tblTransactionDetailAudits { get; set; }
        public virtual DbSet<tblBatchHeader> tblBatchHeaders { get; set; }
        public virtual DbSet<tblBatchHeaderAudit> tblBatchHeaderAudits { get; set; }
        public virtual DbSet<tblGLTransactionDetail> tblGLTransactionDetails { get; set; }
        public virtual DbSet<tblGLTransactionDetailAudit> tblGLTransactionDetailAudits { get; set; }
        public virtual DbSet<tblGeneralLedger> tblGeneralLedgers { get; set; }
        public virtual DbSet<tblGeneralLedgerAudit> tblGeneralLedgerAudits { get; set; }
        public virtual DbSet<tblSoapXML> tblSoapXMLs { get; set; }
    }
}
