//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWS.PayrollVouchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentNumberAudit
    {
        public int AuditID { get; set; }
        public int DocumentID { get; set; }
        public string DocumentType { get; set; }
        public System.DateTime PayPeriodEndingDate { get; set; }
        public string VendorName { get; set; }
        public string VendorNumber { get; set; }
        public string UserCode { get; set; }
        public System.DateTime DocumentCreationDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentStatus { get; set; }
        public string CheckDescription { get; set; }
        public string BankNumber { get; set; }
        public int BatchHeaderID { get; set; }
        public System.DateTime DateModified { get; set; }
        public string WhoModified { get; set; }
    }
}
