//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWS.PayrollVouchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGeneralLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGeneralLedger()
        {
            this.tblGLTransactionDetails = new HashSet<tblGLTransactionDetail>();
        }
    
        public int GLID { get; set; }
        public string BatchNumber { get; set; }
        public string BatchType { get; set; }
        public decimal BatchTotal { get; set; }
        public string GLComments { get; set; }
        public string JournalComments { get; set; }
        public string Ledger { get; set; }
        public string Period { get; set; }
        public string Year { get; set; }
        public string UserCode { get; set; }
        public System.DateTime DateModified { get; set; }
        public string WhoModified { get; set; }
        public string GLType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTransactionDetail> tblGLTransactionDetails { get; set; }
    }
}
