//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWS.PayrollVouchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLTransactionDetail
    {
        public int TransactionID { get; set; }
        public decimal TransactionAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Comments { get; set; }
        public string Fund { get; set; }
        public string ResponsibilityCode { get; set; }
        public string ObjectCode { get; set; }
        public string ProgramCode { get; set; }
        public int GLID { get; set; }
        public System.DateTime DateModified { get; set; }
        public string WhoModified { get; set; }
    
        public virtual tblGeneralLedger tblGeneralLedger { get; set; }
    }
}
