//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWS.PayrollVouchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGeneralSetting
    {
        public int ID { get; set; }
        public string BankNumber { get; set; }
        public string ChildSupportDesc { get; set; }
        public string FilePath { get; set; }
        public string UserCode { get; set; }
        public string VouchersPayableDesc { get; set; }
        public string TempPassword { get; set; }
        public System.DateTime DateModified { get; set; }
        public string WhoModified { get; set; }
    }
}
