//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWS.PayrollVouchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoapXML
    {
        public string BatchType { get; set; }
        public int ID { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public System.DateTime DatePosted { get; set; }
    }
}
